In [20]:
import numpy as np
import pandas as pd
from pprint import pprint
from os import listdir
from os.path import isfile, join
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import RFE

from scipy import stats
import numpy as np
from sklearn import linear_model, svm
dd =pd.read_csv('../braindata/data_3_all.csv',header=0)
data=np.array(dd)
#print(data.shape)
idx_IN_columns = np.append(np.array([3,4]),np.array(range(11,data.shape[1])))
features=data[:,idx_IN_columns]
#features=data[:,11:data.shape[1]]
#features = features.transpose()
features = stats.zscore(features)
#print(features.shape)
y=data[:,5]
#print(y.shape)
#5: ad-smi / 6:mci-smi / 7:adonly-smi / 8:ad-mci / 9:adonly-mci / 10:adonly - adwithsmallvv

ind_num=np.isnan(y)
# print(ind_num.shape)
y_no_nan = y[~ind_num]
features_no_nan = features[~ind_num,:]

# print(y.shape)

y=y_no_nan
features=features_no_nan

model = LogisticRegression(C=1e5)
rfe = RFE(model, 3)
rfe = rfe.fit(features, y)

/Users/yunwang/anaconda/lib/python3.6/site-packages/scipy/stats/stats.py:2247: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [12]:
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load the iris datasets
dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes
model = LogisticRegression(C=1e5)
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(dataset.data, dataset.target)
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False  True  True  True]
[2 1 1 1]

In [13]:
rfe

RFE(estimator=LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False),
  n_features_to_select=3, step=1, verbose=0)

In [24]:
x=['a','b']
x[0]

'a'

In [28]:
import re
s = "Example String"
replaced = re.sub('[ES]', 'a', s)
print(replaced )

axample atring

In [30]:
sort([2,1])

NameError: name 'sort' is not defined

In [31]:
a=[2,1]

In [32]:
a.sort()
a

[1, 2]

In [33]:
n_features = [100,1000,10000,2000,20000,3000,30000,4000,500,5000,6000,7000,8000,9000]
n_features.sort()

In [34]:
n_features

[100,
 500,
 1000,
 2000,
 3000,
 4000,
 5000,
 6000,
 7000,
 8000,
 9000,
 10000,
 20000,
 30000]

In [35]:
    dd =pd.read_csv('../braindata/data_2_conn_select_100.csv',header=0)

In [47]:
import re
s = "../braindata/data_2_conn_select_100.csv"
n_features = [100,1000,10000,2000,20000,3000,30000,4000,500,5000,6000,7000,8000,9000]
n_features.sort()
for i in n_features:
    print(i)
    
    replaced = re.sub('100', str(i), s)
    print(replaced)

100
../braindata/data_2_conn_select_100.csv
500
../braindata/data_2_conn_select_500.csv
1000
../braindata/data_2_conn_select_1000.csv
2000
../braindata/data_2_conn_select_2000.csv
3000
../braindata/data_2_conn_select_3000.csv
4000
../braindata/data_2_conn_select_4000.csv
5000
../braindata/data_2_conn_select_5000.csv
6000
../braindata/data_2_conn_select_6000.csv
7000
../braindata/data_2_conn_select_7000.csv
8000
../braindata/data_2_conn_select_8000.csv
9000
../braindata/data_2_conn_select_9000.csv
10000
../braindata/data_2_conn_select_10000.csv
20000
../braindata/data_2_conn_select_20000.csv
30000
../braindata/data_2_conn_select_30000.csv

In [38]:
    dd =pd.read_csv(replaced,header=0)

In [39]:
dd

,subject,dx.1ad.2mci.3smi,dx2.1adonly.2adwithsmallvv.3mci.4.smi,SEX,AGE,dx_ad_smi,dx_mci_smi,dx_ad_mci,dx_adonly_smi,dx_adonly_mci,...,V26762.1,V26774.1,V26797.1,V26798.1,V26831.1,V26844.1,V26851.1,V26858.1,V26864.1,V26887.1
0,10004362,3,4,2,66,0.0,0.0,NaN,0.0,NaN,...,75.037,84.718,74.381,67.761,58.856,63.305,73.896,52.666,131.690,65.292
1,10005426,1,1,2,90,1.0,NaN,1.0,1.0,1.0,...,200.430,187.200,202.240,186.060,157.400,109.810,177.090,147.860,139.140,164.060
2,10011000,2,3,2,80,NaN,1.0,0.0,NaN,0.0,...,185.970,198.330,177.480,162.900,79.959,71.799,141.750,109.550,135.390,123.800
3,10014793,1,1,2,76,1.0,NaN,1.0,1.0,1.0,...,195.350,182.220,207.350,172.950,180.710,129.360,180.280,131.680,140.540,169.200
4,10015858,2,3,1,69,NaN,1.0,0.0,NaN,0.0,...,194.430,188.860,198.300,158.810,171.440,139.040,167.190,129.160,128.880,140.580
5,10016158,3,4,2,73,0.0,0.0,NaN,0.0,NaN,...,168.940,55.551,128.980,92.499,48.937,54.240,120.860,51.356,95.933,45.653
6,10021984,2,3,2,75,NaN,1.0,0.0,NaN,0.0,...,192.440,235.830,193.230,152.430,153.420,134.740,164.090,136.650,139.190,150.150
7,10029184,1,1,1,93,1.0,NaN,1.0,1.0,1.0,...,198.210,151.350,163.410,172.130,155.020,119.280,176.110,84.825,123.060,146.220
8,10031650,2,3,2,73,NaN,1.0,0.0,NaN,0.0,...,190.840,176.360,178.330,159.190,156.000,117.060,168.730,133.270,135.530,155.790
9,10038992,2,3,1,77,NaN,1.0,0.0,NaN,0.0,...,182.650,179.630,189.200,171.840,159.290,130.870,162.710,139.530,137.590,150.300
10,10040504,2,3,2,50,NaN,1.0,0.0,NaN,0.0,...,176.220,203.720,172.350,158.610,152.020,90.926,155.690,139.820,114.360,136.420
11,10049700,2,3,1,76,NaN,1.0,0.0,NaN,0.0,...,207.210,225.340,220.010,173.350,190.900,123.030,178.010,140.000,140.480,162.220
12,10059651,2,3,2,58,NaN,1.0,0.0,NaN,0.0,...,177.950,188.240,176.880,140.820,158.920,113.190,158.910,150.350,129.810,142.720
13,10061549,3,4,2,84,0.0,0.0,NaN,0.0,NaN,...,177.560,174.520,170.020,167.990,149.590,40.649,157.750,173.460,123.430,148.070
14,10088406,3,4,2,65,0.0,0.0,NaN,0.0,NaN,...,82.919,0.000,108.160,57.867,48.313,72.928,68.358,0.000,0.000,47.631
15,10090214,2,3,2,70,NaN,1.0,0.0,NaN,0.0,...,179.500,175.420,188.100,163.160,194.190,128.120,161.560,127.820,124.050,144.210
16,10094549,3,4,2,71,0.0,0.0,NaN,0.0,NaN,...,165.000,61.373,170.440,146.070,56.731,59.251,181.590,67.908,129.160,151.710
17,10095070,1,2,2,76,1.0,NaN,1.0,NaN,NaN,...,186.790,220.350,199.240,160.390,155.010,118.710,153.010,154.130,130.640,137.600
18,10120000,1,2,2,84,1.0,NaN,1.0,NaN,NaN,...,192.460,197.580,186.460,168.870,0.000,124.550,206.460,155.770,143.570,145.900
19,10123696,1,1,2,73,1.0,NaN,1.0,1.0,1.0,...,196.090,191.040,195.210,159.560,174.230,130.620,182.230,161.900,142.130,154.600
20,10126425,1,2,1,72,1.0,NaN,1.0,NaN,NaN,...,193.080,131.670,189.110,167.590,154.010,122.940,167.390,110.640,133.080,141.900
21,10146748,2,3,2,63,NaN,1.0,0.0,NaN,0.0,...,182.530,221.360,189.150,164.040,160.590,125.910,165.340,136.950,131.700,144.830
22,10161620,1,2,2,79,1.0,NaN,1.0,NaN,NaN,...,195.880,193.750,191.990,174.110,109.470,120.870,175.870,116.270,137.380,150.230
23,10164891,3,4,2,73,0.0,0.0,NaN,0.0,NaN,...,156.560,57.698,109.620,119.770,51.069,55.142,63.496,59.449,57.860,52.634
24,10170612,1,2,2,92,1.0,NaN,1.0,NaN,NaN,...,188.800,105.400,177.000,158.920,158.120,113.850,171.000,116.990,141.700,143.480
25,10180319,3,4,2,74,0.0,0.0,NaN,0.0,NaN,...,158.270,127.420,134.210,126.160,53.147,78.734,66.500,51.940,63.094,78.536
26,10186209,1,2,2,94,1.0,NaN,1.0,NaN,NaN,...,183.150,203.050,189.770,153.910,163.380,118.030,167.630,128.290,133.840,138.510
27,10193631,3,4,2,63,0.0,0.0,NaN,0.0,NaN,...,170.100,64.775,160.370,134.330,166.210,69.628,157.790,55.157,131.250,139.520
28,10197798,3,4,2,72,0.0,0.0,NaN,0.0,NaN,...,63.441,0.000,83.670,60.748,38.384,55.709,59.493,0.000,0.000,49.390
29,10208089,2,3,1,77,NaN,1.0,0.0,NaN,0.0,...,198.290,208.890,191.290,181.400,189.350,130.590,178.380,136.040,143.420,161.430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,11357113,1,1,2,71,1.0,NaN,1.0,1.0,1.0,...,198.060,189.670,209.360,168.850,163.890,65.275,165.950,158.780,126.880,150.290
182,11357486,2,3,1,76,NaN,1.0,0.0,NaN,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
183,11358460,1,1,2,70,1.0,NaN,1.0,1.0,1.0,...,172.180,206.840,174.590,141.780,161.540,126.410,156.420,133.660,126.570,135.790
184,11368796,2,3,1,62,NaN,1.0,0.0,NaN,0.0,...,140.480,80.349,138.080,146.970,56.423,56.948,93.284,49.810,54.738,60.276
185,11368990,1,1,1,76,1.0,NaN,1.0,1.0,1.0,...,198.280,208.910,195.520,183.010,141.760,75.811,176.570,79.210,116.580,161.810
186,11370621,2,3,2,71,NaN,1.0,0.0,NaN,0.0,...,62.306,0.000,97.815,52.809,89.479,0.000,54.758,0.000,0.000,90.172
187,11371140,2,3,2,72,NaN,1.0,0.0,NaN,0.0,...,182.390,73.627,185.410,121.810,53.624,49.773,165.540,50.140,127.260,149.660
188,11372886,2,3,2,75,NaN,1.0,0.0,NaN,0.0,...,140.820,154.930,140.020,127.110,40.917,67.981,55.390,58.371,87.067,62.023
189,11374870,3,4,1,77,0.0,0.0,NaN,0.0,NaN,...,166.980,54.164,163.550,147.960,99.046,126.030,141.340,164.570,135.140,130.420
190,11378627,1,1,2,82,1.0,NaN,1.0,1.0,1.0,...,181.770,207.240,175.840,158.060,161.500,125.810,157.470,164.270,127.100,143.500
191,11380871,1,1,2,88,1.0,NaN,1.0,1.0,1.0,...,184.990,147.950,189.850,171.690,151.690,124.020,165.560,128.920,137.280,147.060
192,11382807,1,1,2,78,1.0,NaN,1.0,1.0,1.0,...,192.210,182.220,192.980,152.570,175.650,119.710,169.120,147.710,141.570,147.990
193,11384465,2,3,1,73,NaN,1.0,0.0,NaN,0.0,...,56.162,75.172,72.713,74.494,37.185,71.944,57.533,0.000,0.000,48.427
194,11388743,3,4,2,78,0.0,0.0,NaN,0.0,NaN,...,133.510,171.560,187.540,91.056,50.566,60.454,89.770,59.220,91.583,80.120
195,11394186,2,3,2,83,NaN,1.0,0.0,NaN,0.0,...,52.560,0.000,75.507,60.997,45.153,91.112,50.418,0.000,0.000,51.337
196,11394260,2,3,2,76,NaN,1.0,0.0,NaN,0.0,...,180.390,44.949,115.630,87.586,75.744,59.192,161.650,56.999,115.280,142.580
197,11398446,1,1,2,62,1.0,NaN,1.0,1.0,1.0,...,177.080,206.150,176.390,157.950,166.240,92.233,160.500,80.963,124.460,135.200
198,11400255,3,4,2,72,0.0,0.0,NaN,0.0,NaN,...,79.348,81.226,97.282,60.794,36.928,67.137,70.075,53.339,69.958,40.004
199,11404932,2,3,1,67,NaN,1.0,0.0,NaN,0.0,...,148.760,61.090,167.050,80.433,47.566,52.197,155.360,0.000,104.600,119.550
200,11405532,1,1,2,73,1.0,NaN,1.0,1.0,1.0,...,193.450,86.898,194.320,184.970,184.270,184.090,166.770,146.590,141.780,185.960
201,11405963,1,2,2,75,1.0,NaN,1.0,NaN,NaN,...,198.320,223.630,194.070,169.320,63.103,46.674,158.430,108.760,131.830,152.260
202,11406091,1,1,2,82,1.0,NaN,1.0,1.0,1.0,...,191.040,212.900,192.840,163.810,159.510,112.820,164.660,65.378,120.850,147.500
203,11406849,1,1,1,69,1.0,NaN,1.0,1.0,1.0,...,184.400,193.960,176.250,157.900,166.610,115.540,166.350,139.840,132.300,148.280
204,11411665,3,4,1,84,0.0,0.0,NaN,0.0,NaN,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
205,11412571,1,1,2,75,1.0,NaN,1.0,1.0,1.0,...,185.900,205.160,181.280,146.380,157.040,138.240,152.590,139.480,124.900,138.680
206,11413364,1,2,1,81,1.0,NaN,1.0,NaN,NaN,...,197.390,197.860,190.550,157.290,164.960,126.040,165.600,143.460,150.060,156.430
207,11414215,1,1,1,77,1.0,NaN,1.0,1.0,1.0,...,198.980,200.070,191.410,180.920,165.970,112.440,170.480,138.800,132.800,161.740
208,11416827,2,3,2,58,NaN,1.0,0.0,NaN,0.0,...,47.555,0.000,73.967,59.103,40.771,46.552,43.361,0.000,0.000,45.527
209,11421208,1,2,2,82,1.0,NaN,1.0,NaN,NaN,...,188.810,195.160,190.370,173.060,176.940,141.830,168.360,130.910,139.650,161.520
210,11433763,3,4,2,62,0.0,0.0,NaN,0.0,NaN,...,82.566,0.000,91.038,73.269,49.424,93.169,59.069,52.848,132.140,59.811